server:
    port: 9090
spring:
  output:
      ansi:
        enabled: ALWAYS
  application:
      name: Catalogue Services
  datasource:
      url: jdbc:h2:~/cataloguedb
      driverClassName: org.h2.Driver
      username: sa
  h2:
      console.enabled: true
  jpa:
      show-sql: false
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      hibernate:
          ddl-auto: create-drop
      properties:
          hibernate:
                format-sql: true
  sql:
      init:
        mode: always
        data-locations: classpath:init.sql